# Generated by Django 5.2.8 on 2025-11-21 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='habit_photos/'),
        ),
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_value',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric target, e.g. 8 glasses, 20 pages, 5 km', null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit for target e.g. glasses, pages, km', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
