# Generated by Django 5.2.8 on 2025-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0003_alter_habit_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_value',
            field=models.CharField(blank=True, help_text="Target value (alphanumeric OK), e.g. '3 liters', '20 pages'", max_length=100, null=True),
        ),
    ]
